# Format: RequestClass=ResponseClass:field1=field1Response,field2=field2Response

CreateUserRequest=CreateUserResponse:username=username,role=role
DepositMoneyRequest=DepositMoneyResponse:id=id,balance=balance
TransferMoneyRequest=TransferMoneyResponse:senderAccountId=senderAccountId,receiverAccountId=receiverAccountId,amount=amount
